### PR TITLE
New keyword data structure

### PR DESCRIPTION
**Pull request by TroyDanielFZ**
* Support nested highlight
* Bug fix: innerHTML deleted unintentionally
* Bug fix: Word boundary not working for keyword-list
* <tag>DEV</tag> Change keyword data structure and update the version to "2.8.0"

Sorry, late for the dinner.
After several busy days, I finally manage to work this out.

In this PR, #25, #23  should be solved. As for #26, I'm still confused after skimming it. I'd like to ask @yiminzme to test, whether this PR meets the requirement for #26. Thanks in advance.

### CODE REVIEW

**Comment by TroyDanielFZ** [comment]
Really, I'm not familiar with Github and git, so I might learn power git ver 2 and the instructions for github someday, hopefully.

**Comment by yiminzme** [comment]
@TroyDanielFZ Awesome work!
Surely you can learn version control tools easily :-)

I have tested your updated version 7504ef6feeade3d88f43ed83155685e230aa62cd. love the two features added.
As for #26, it is not covered. I can fix them based on your code after you finish coding (to avoid code conflict).

🙇‍♂️

**Comment by yiminzme** [comment]
For #23, ideally, we want the highlights of both "asd" and "asdf" to be always visible. But only "asdf" is actually visible when I type "asd,asdf" unless I press your refresh button or reload the page.

**Comment by TroyDanielFZ** [comment]
image
On my computer, it works well as I paste the keyword-string `asd,asdf` into the box, the highlighted result is shown above.

Besides, I think the refresh button is quite ugly. I'm not good at the UI design, can you help with this?

I've done with the code at this point.

**Comment by yiminzme** [comment]
@TroyDanielFZ 
I have merged your code and changed the UI a bit. 👍

**Comment by TroyDanielFZ** [comment]
Thks.

**Pull request merged**
